ruby/config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    collection do
      get :export
    end
  end

  resources :properties

  get '/oauth', to: 'oauth/authorization#authorize'
  get '/oauth/callback', to: 'oauth/authorization#callback'
  get '/login', to: 'oauth/authorization#login'
  root to: 'contacts#index'
end

ruby/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ExceptionHandler

  before_action :check_env_variables

  private

  def check_env_variables
    missing_vars = %w[HUBSPOT_CLIENT_ID HUBSPOT_CLIENT_SECRET].select { |var| ENV[var].blank? }
    raise(ExceptionHandler::HubspotError.new, "Please specify #{missing_vars.join(', ')} in .env") if missing_vars.present?
  end
end

ruby/app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  class HubspotError < StandardError; end

  included do
    rescue_from HubspotError do |error|
      @error = error
      render template: 'contacts/index'
    end
  end
end

ruby/app/controllers/contacts_controller.rb
require 'hubspot-api-client'

class ContactsController < ApplicationController
  before_action :authorize
  def index
    # https://developers.hubspot.com/docs/methods/contacts/get_contacts
    @contacts = if params[:search].present?
      @search_q = params[:search]
      Services::Hubspot::Contacts::Search.new(session[:tokens][:access_token], email: @search_q).call
    else
      # https://developers.hubspot.com/docs/methods/contacts/get_contacts
      Services::Hubspot::Contacts::GetPage.new(limit: 100, access_token: session[:tokens][:access_token]).call.sort_by(&:created_at).reverse
    end
  end

  def show
    @contact = Services::Hubspot::Contacts::GetById.new(params[:id], session[:tokens][:access_token]).call
    @owners = Services::Hubspot::Owners::GetAll.new(session[:tokens][:access_token]).call
  end

  def create
    Services::Hubspot::Contacts::Create.new(session[:tokens][:access_token],  email: params[:email]).call
    redirect_to :contacts
  rescue Hubspot::Crm::Contacts::ApiError => e
    error_message = JSON.parse(e.response_body)['message']
    redirect_to new_contact_path, flash: { error: error_message }
  end

  def update
    @contact = Services::Hubspot::Contacts::GetById.new(params[:id], session[:tokens][:access_token]).call
    Services::Hubspot::Contacts::Update.new(session[:tokens][:access_token], params[:id], contact_params).call
    redirect_to :contacts
  rescue Hubspot::Crm::Contacts::ApiError => e
    error_message = JSON.parse(e.response_body)['message']
    redirect_to contact_path(params[:id]), flash: { error: error_message }
  end

  def export
    respond_to do |format|
      format.html
      format.csv do
        send_data(
          Services::Hubspot::Contacts::Export.new(session[:tokens][:access_token]).call,
          filename: "contacts-#{Date.today}.csv"
        )
      end
    end
  end

  def destroy
    @contact = Services::Hubspot::Contacts::GetById.new(params[:id], session[:tokens][:access_token]).call
    Services::Hubspot::Contacts::Destroy.new(params[:id], session[:tokens][:access_token]).call
    redirect_back(fallback_location: root_path, notice: "Contact ##{@contact.id} was successfully destroyed.")
  end

  private

  def contact_params
    params.require(:contact).permit(@contact.properties.keys).to_hash
  end

  def authorize
    redirect_to login_path and return if session['tokens'].blank?

    session['tokens'] = Services::Authorization::Tokens::Refresh.new(tokens: session['tokens'], request: request).call
    Services::Authorization::AuthorizeHubspot.new(tokens: session['tokens']).call
  end
end

ruby/app/controllers/oauth/authorization_controller.rb
module Oauth
  class AuthorizationController < ApplicationController
    def authorize
      url = Services::Authorization::GetAuthorizationUri.new(request: request).call
      redirect_to url
    end

    def callback
      session[:tokens] = Services::Authorization::Tokens::Generate.new(
        code: params[:code],
        request: request
      ).call
      Services::Authorization::AuthorizeHubspot.new(tokens: session[:tokens]).call
      redirect_to '/contacts'
    end

    def login;end
  end
end

ruby/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/app/views/contacts/index.html.erb
<div class="container">
  <% if @error.present? %>
    <h3><%= @error.message %></h3>
  <% else %>
    <div class='contact-new-button'>
      <pre>
        <p>Create contact</p>
        <p># app/lib/services/hubspot/contacts/create.rb</p>

        <p>Export to CSV</p>
        <p># app/lib/services/hubspot/contacts/export.rb</p>
      </pre>
      <%= link_to('New Contact', new_contact_path, class: 'button', id: 'new-contact') %>
      <%= link_to('Export To CSV', export_contacts_path(format: :csv), class: 'button', id: 'export') %>
    </div>

    <%= form_tag('/contacts', method: :get, class: 'contacts') do %>
      <%= text_field_tag(:search, @search_q, placeholder: 'Search by email..', id: 'search') %>
    <% end %>
    <pre>
    <p>Search</p>
    <p># app/lib/services/hubspot/contacts/search.rb</p>
    </pre>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <table class="contacts">
      <thead>
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Name</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr class="contact">
            <td>
              <a href="/contacts/<%= contact.id %>">
                <div class="contact-info contact-id">
                  <%= contact.id %>
                </div>
              </a>
            </td>
            <td>
              <a href="/contacts/<%= contact.id %>">
                <div class="contact-info contact-email">
                  <%= contact.properties['email'] %>
                </div>
              </a>
            </td>
            <td>
              <a href="/contacts/<%= contact.id %>">
                <div class="contact-info contact-fullname">
                  <%= contact.properties['fullname'].present? ? contact.properties['fullname'] : contact.properties['email'] %>
                </div>
              </a>
            </td>
            <td>
              <%= button_to "delete",
                { controller: :contacts, action: :destroy, id: contact.id },
                method: :delete,
                form_class: 'delete-button'
              %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <pre>
    <p>Delete</p>
    <p># app/lib/services/hubspot/contacts/destroy.rb</p>
  </pre>
</div>

ruby/app/views/contacts/new.html.erb
<div class="container">
  <% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>

  <div class="row contact-create">
      <div class="column column-20"></div>
      <div class="column column-60">
        <h3>Properties</h3>
        <%= form_tag('/contacts', method: 'post') do %>
          <%= label_tag(:email, "Email") %>
          <%= text_field_tag(:email, @email) %>
          <%= submit_tag("Save") %>
        <% end %>
      </div>
      <div class="column column-20"></div>
  </div>
</div>

ruby/app/views/contacts/show.html.erb
<div class="container">
  <% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>
  <div class="row">
    <div class="column">
      <pre>
        <p>Show</p>
        <p># app/lib/services/hubspot/contacts/show.rb</p>
      </pre>
      <h3>Properties</h3>
      <%= form_for :contact, url: "/contacts/#{params[:id]}", method: 'put' do |form| %>
        <% @contact.properties.each do |property_key, property_value| %>
          <%= label(:contact, property_key, property_key) %>
            <%= text_field(:contact, property_key, value: property_value) %>
        <% end %>

        <pre>
          <p>Update</p>
          <p># app/lib/services/hubspot/contacts/update.rb</p>
        </pre>
        <%= submit_tag("Save", class: 'button-primary') %>
      <% end %>
    </div>
    <div class="column">
      </div>
  </div>
</div>

ruby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>HubSpot Ruby sample contacts app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/milligram/1.3.0/milligram.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/header"%>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>

ruby/app/views/oauth/authorization/login.html.erb
<div class="container">
  <pre>
    <p>// app/lib/services/authorization/get_authorization_uri.rb - Generate URL for OAuth</p>

    <p>::Hubspot::OAuthHelper.authorize_url(</p>
    <p>  client_id: 'client_id',</p>
    <p>  redirect_uri: redirect_uri,</p>
    <p>  scope: %w[contacts]</p>
    <p>)</p>
  </pre>
  <h3 class="text-center">In order to continue please authorize via OAuth</h3>
  <div class="row authorize-button">
      <a class="button" href="/oauth">Authorize</a>
  </div>
</div>

ruby/app/views/shared/_header.html.erb
<nav class="navigation">
  <div class="container">
    <a class="navigation-title" href="/">
      <h3 class="title">HubSpot Ruby Sample OAuth App</h3>
    </a>
    <ul class="navigation-list float-right">
      <li class="navigation-item">
        <a id="contacts-list" class="navigation-link" href="/contacts">Contacts</a>
      </li>
      <li class="navigation-item">
        <a class="navigation-link" href="/oauth">OAuth2</a>
      </li>
    </ul>
  </div>
</nav>