python/src/app.py
from flask import Flask, redirect, url_for

import routes

app = Flask(__name__)

app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'

app.register_blueprint(routes.oauth, url_prefix="/oauth")
app.register_blueprint(routes.contacts, url_prefix="/contacts")


@app.route("/")
def contacts():
    return redirect(url_for("contacts.list"))


if __name__ == "__main__":
    app.run(host="0.0.0.0", debug=True)

python/src/auth.py
from flask import redirect, url_for
from functools import wraps
from helpers.oauth import is_authorized


def auth_required(func):
    @wraps(func)
    def check_auth(*args, **kwargs):
        if not is_authorized():
            return redirect(url_for("oauth.login"))

        return func(*args, **kwargs)

    return check_auth

python/src/routes/contacts.py
from flask import Blueprint, render_template
from helpers.hubspot import create_client
from auth import auth_required


module = Blueprint("contacts", __name__)


@module.route("/")
@auth_required
def list():
    hubspot = create_client()
    contacts_page = hubspot.crm.contacts.basic_api.get_page()

    return render_template("contacts/list.html", contacts=contacts_page.results)

python/src/routes/oauth.py
from flask import Blueprint, render_template, redirect, request
from hubspot.utils.oauth import get_auth_url
import os
from helpers.oauth import save_tokens, get_redirect_uri
from helpers.hubspot import create_client

module = Blueprint("oauth", __name__)


@module.route("/login")
def login():
    return render_template("oauth/login.html")


@module.route("/authorize")
def authorize():
    auth_url = get_auth_url(
        scopes=("contacts",),
        client_id=os.environ.get("HUBSPOT_CLIENT_ID"),
        redirect_uri=get_redirect_uri(),
    )

    return redirect(auth_url)


@module.route("/callback")
def callback():
    hubspot = create_client()
    tokens_response = hubspot.auth.oauth.default_api.create_token(
        grant_type="authorization_code",
        code=request.args.get("code"),
        redirect_uri=get_redirect_uri(),
        client_id=os.environ.get("HUBSPOT_CLIENT_ID"),
        client_secret=os.environ.get("HUBSPOT_CLIENT_SECRET"),
    )
    save_tokens(tokens_response)

    return redirect("/")

python/src/templates/contacts/list.html
{% extends "layout.html" %}

{% block content %}

<pre>
// src/routes/contacts.py
client = HubSpot(access_token='access_token')
contacts_page = client.crm.contacts.basic_api.get_page()
</pre>

<table class="contacts-list">
    <thead>
    <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Name</th>
    </tr>
    </thead>
    <tbody>

    {% for contact in contacts %}
        <tr>
            <td>{{ contact.id }}</td>
            <td>{{ contact.properties.email }}</td>
            <td>{{ contact.properties.firstname ~ ' ' ~ contact.properties.lastname}}</td>
        </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}

python/src/templates/oauth/login.html
{% extends "layout.html" %}

{% block content %}
<pre>
// src/routes/oauth.py - Generate URL for OAuth
from hubspot.utils.oauth import get_auth_url
auth_url = get_auth_url(
    scopes=('contacts',),
    client_id=os.environ.get('HUBSPOT_CLIENT_ID'),
    redirect_uri=get_redirect_uri(),
)
</pre>

<h3 class="text-center">In order to continue please authorize via OAuth</h3>
<div class="row authorize-button">
    <a class="button" href="{{ url_for('oauth.authorize') }}">Authorize</a>
</div>
{% endblock %}